### ISSUE TITLE
Question about the generated samples

### ISSUE THREAD

**Issue by dmortem** [ewsheng/nlg-bias#3]
Hi,

Thanks for your nice code! 

Recently I tried to generate new sentences using GPT-2, and test the regard score of these sentences. However, my generated sentences tend to be quite negative (over 60%) while in your 'small_gpt2_generated_samples.tsv', the negative ratio is relative low, as described in your paper. 

Therefore, I wonder how you use GPT2 to generate new samples? For me, I use [Pytorch transformers example](https://github.com/huggingface/transformers/blob/master/examples/text-generation/run_generation.py) to generate. I really appreciate any advice you can give. Thank you!

**Comment by dmortem** [comment]
Also, do you enumerate different random seeds to generate different samples for each context? Since the context we use is short, if we fix the seed, the diversity of the generated samples is quite low even though we use sampling instead of greedy search. Thank you.

**Comment by ewsheng** [comment]
Sorry for the late response! You can try adjusting the `temperature` and either`top-k` or `top-p` parameters to get more diverse samples. In our work, we used `temperature=0.7` and `k=40` and don't change the random seed.
