### ISSUE TITLE
Request for annotated data

### ISSUE THREAD

**Issue by hongcheki** [ewsheng/nlg-bias#5]
Hello @ewsheng 

Thanks for your excellent model!

I've used your updated regard classifier trained on an additional annotated dataset.
I want to access the additional dataset, but it hasn't been uploaded.

I would really appreciate it if you could upload an additional annotated dataset.
Thank you!

**Comment by ewsheng** [comment]
Thank you for your interest, and sorry for the delay! The data we used to train the latest (Dec. 2020) v2 model can be found [here](https://drive.google.com/drive/folders/1cxeVagS8eJilY3Yg_vYYhZJIcamYWpeA?usp=sharing). Each train/dev/test file includes both the v1 data and additional annotated data. Demographics in the data are masked (unfortunately I don't have the unmasked versions anymore).

**Comment by hongcheki** [comment]
It would be helpful for me! Thank you!
